
CREATE DATABASE IF NOT EXISTS avefenix CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE avefenix;

CREATE TABLE IF NOT EXISTS productos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(40) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  categoria VARCHAR(80) NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  precio_base DECIMAL(12,2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  umbral_bajo INT NOT NULL DEFAULT 5,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dni VARCHAR(20),
  nombre VARCHAR(120) NOT NULL,
  contacto VARCHAR(120),
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ventas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(40) NOT NULL,
  cliente_id INT,
  cantidad INT NOT NULL,
  canal VARCHAR(20) NOT NULL, 
  total DECIMAL(12,2) NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id),
  FOREIGN KEY (sku) REFERENCES productos(sku)
);
